version: 2.1
orbs:
  node: circleci/node@1.1
jobs:
  build:
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - add_ssh_keys:
          fingerprints:
            - "42:e8:f4:35:2f:ec:da:fd:3f:e3:cd:6e:f1:42:30:b3"
      - checkout
      - restore_cache:
          keys:
            - dependencies_xh
      - run:
          name: Install
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependencies_xh
      - run:
          name: Build
          command: npm run build
      - run:
          name: Prepare shell commands
          # shell chmod +x 赋予执行权限
          # 执行shell脚本
          command: chmod +x scripts/deploy.sh
      - run:
          name: Run Deploy to Github pages
          command: ./scripts/deploy.sh
